//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from StartupStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class StartupStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.StartupStrings", typeof(StartupStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string SilentUpdate_TimeRange => ResourceManager.GetString(nameof(SilentUpdate_TimeRange), _resourceCulture);

        public static string AutoUpdateHint => ResourceManager.GetString(nameof(AutoUpdateHint), _resourceCulture);

        public static string EnableNibMode => ResourceManager.GetString(nameof(EnableNibMode), _resourceCulture);

        public static string EnableNibModeHint => ResourceManager.GetString(nameof(EnableNibModeHint), _resourceCulture);

        public static string ExternalProtocol => ResourceManager.GetString(nameof(ExternalProtocol), _resourceCulture);

        public static string ExternalProtocolHint => ResourceManager.GetString(nameof(ExternalProtocolHint), _resourceCulture);

        public static string StartupMode => ResourceManager.GetString(nameof(StartupMode), _resourceCulture);

        public static string StartupModeHint => ResourceManager.GetString(nameof(StartupModeHint), _resourceCulture);

        public static string StartupMode_Default => ResourceManager.GetString(nameof(StartupMode_Default), _resourceCulture);

        public static string StartupMode_Faster => ResourceManager.GetString(nameof(StartupMode_Faster), _resourceCulture);

        public static string StartupMode_Fastest => ResourceManager.GetString(nameof(StartupMode_Fastest), _resourceCulture);

        public static string FixVersionHint => ResourceManager.GetString(nameof(FixVersionHint), _resourceCulture);

        public static string FoldAtStartup => ResourceManager.GetString(nameof(FoldAtStartup), _resourceCulture);

        public static string FoldAtStartupHint => ResourceManager.GetString(nameof(FoldAtStartupHint), _resourceCulture);

        public static string NoBorderMode => ResourceManager.GetString(nameof(NoBorderMode), _resourceCulture);

        public static string NoBorderModeHint => ResourceManager.GetString(nameof(NoBorderModeHint), _resourceCulture);

        public static string NoFocusMode => ResourceManager.GetString(nameof(NoFocusMode), _resourceCulture);

        public static string NoFocusModeHint => ResourceManager.GetString(nameof(NoFocusModeHint), _resourceCulture);

        public static string PPTOnlyMode => ResourceManager.GetString(nameof(PPTOnlyMode), _resourceCulture);

        public static string PPTOnlyModeHint => ResourceManager.GetString(nameof(PPTOnlyModeHint), _resourceCulture);

        public static string RunAtStartup => ResourceManager.GetString(nameof(RunAtStartup), _resourceCulture);

        public static string RunAtStartupHint => ResourceManager.GetString(nameof(RunAtStartupHint), _resourceCulture);

        public static string SilentUpdateFullHint => ResourceManager.GetString(nameof(SilentUpdateFullHint), _resourceCulture);

        public static string SilentUpdateHint => ResourceManager.GetString(nameof(SilentUpdateHint), _resourceCulture);

        public static string SmartUpdate => ResourceManager.GetString(nameof(SmartUpdate), _resourceCulture);

        public static string SmartUpdateHint => ResourceManager.GetString(nameof(SmartUpdateHint), _resourceCulture);

        public static string Start => ResourceManager.GetString(nameof(Start), _resourceCulture);

        public static string Startup_Behavior => ResourceManager.GetString(nameof(Startup_Behavior), _resourceCulture);

        public static string TimePeriodHint => ResourceManager.GetString(nameof(TimePeriodHint), _resourceCulture);

        public static string TopMost => ResourceManager.GetString(nameof(TopMost), _resourceCulture);

        public static string TopMostHint => ResourceManager.GetString(nameof(TopMostHint), _resourceCulture);

        public static string TopMostMode => ResourceManager.GetString(nameof(TopMostMode), _resourceCulture);

        public static string TopMostMode_Normal => ResourceManager.GetString(nameof(TopMostMode_Normal), _resourceCulture);

        public static string TopMostMode_Normal_RestartRequired => ResourceManager.GetString(nameof(TopMostMode_Normal_RestartRequired), _resourceCulture);

        public static string TopMostMode_RestartAsAdmin => ResourceManager.GetString(nameof(TopMostMode_RestartAsAdmin), _resourceCulture);

        public static string TopMostMode_CurrentUIAccessNormal => ResourceManager.GetString(nameof(TopMostMode_CurrentUIAccessNormal), _resourceCulture);

        public static string TopMostMode_RestartAsNormal => ResourceManager.GetString(nameof(TopMostMode_RestartAsNormal), _resourceCulture);

        public static string TopMostMode_UIA => ResourceManager.GetString(nameof(TopMostMode_UIA), _resourceCulture);

        public static string TopMostMode_UIA_RestartRequired => ResourceManager.GetString(nameof(TopMostMode_UIA_RestartRequired), _resourceCulture);

        public static string UIAMode_Label => ResourceManager.GetString(nameof(UIAMode_Label), _resourceCulture);

        public static string UIAMode_UserToken => ResourceManager.GetString(nameof(UIAMode_UserToken), _resourceCulture);

        public static string UIAMode_ProcessToken => ResourceManager.GetString(nameof(UIAMode_ProcessToken), _resourceCulture);

        public static string UIAMode_Description => ResourceManager.GetString(nameof(UIAMode_Description), _resourceCulture);

        public static string UpdateChannel => ResourceManager.GetString(nameof(UpdateChannel), _resourceCulture);

        public static string UpdateChannelHint => ResourceManager.GetString(nameof(UpdateChannelHint), _resourceCulture);

        public static string UpdatePackageArchitecture => ResourceManager.GetString(nameof(UpdatePackageArchitecture), _resourceCulture);

        public static string UpdatePackageArchitectureHint => ResourceManager.GetString(nameof(UpdatePackageArchitectureHint), _resourceCulture);
    }
}