//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from StorageStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class StorageStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.StorageStrings", typeof(StorageStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AutoSave_Title => ResourceManager.GetString(nameof(AutoSave_Title), _resourceCulture);

        public static string Backup_AutoBeforeUpdate => ResourceManager.GetString(nameof(Backup_AutoBeforeUpdate), _resourceCulture);

        public static string Backup_AutoPeriodic => ResourceManager.GetString(nameof(Backup_AutoPeriodic), _resourceCulture);

        public static string Backup_Desc => ResourceManager.GetString(nameof(Backup_Desc), _resourceCulture);

        public static string Backup_Interval => ResourceManager.GetString(nameof(Backup_Interval), _resourceCulture);

        public static string Backup_Interval_14Days => ResourceManager.GetString(nameof(Backup_Interval_14Days), _resourceCulture);

        public static string Backup_Interval_1Day => ResourceManager.GetString(nameof(Backup_Interval_1Day), _resourceCulture);

        public static string Backup_Interval_30Days => ResourceManager.GetString(nameof(Backup_Interval_30Days), _resourceCulture);

        public static string Backup_Interval_3Days => ResourceManager.GetString(nameof(Backup_Interval_3Days), _resourceCulture);

        public static string Backup_Interval_7Days => ResourceManager.GetString(nameof(Backup_Interval_7Days), _resourceCulture);

        public static string Backup_Interval_DefaultHint => ResourceManager.GetString(nameof(Backup_Interval_DefaultHint), _resourceCulture);

        public static string Backup_Manual => ResourceManager.GetString(nameof(Backup_Manual), _resourceCulture);

        public static string Backup_Restore => ResourceManager.GetString(nameof(Backup_Restore), _resourceCulture);

        public static string Backup_Title => ResourceManager.GetString(nameof(Backup_Title), _resourceCulture);

        public static string Storage_AutoDeleteTitle => ResourceManager.GetString(nameof(Storage_AutoDeleteTitle), _resourceCulture);

        public static string Storage_AutoSaveInk => ResourceManager.GetString(nameof(Storage_AutoSaveInk), _resourceCulture);

        public static string Storage_AutoSaveInkOnScreenshot => ResourceManager.GetString(nameof(Storage_AutoSaveInkOnScreenshot), _resourceCulture);

        public static string Storage_AutoSaveInterval => ResourceManager.GetString(nameof(Storage_AutoSaveInterval), _resourceCulture);

        public static string Storage_AutoSaveInterval_10Min => ResourceManager.GetString(nameof(Storage_AutoSaveInterval_10Min), _resourceCulture);

        public static string Storage_AutoSaveInterval_15Min => ResourceManager.GetString(nameof(Storage_AutoSaveInterval_15Min), _resourceCulture);

        public static string Storage_AutoSaveInterval_1Min => ResourceManager.GetString(nameof(Storage_AutoSaveInterval_1Min), _resourceCulture);

        public static string Storage_AutoSaveInterval_30Min => ResourceManager.GetString(nameof(Storage_AutoSaveInterval_30Min), _resourceCulture);

        public static string Storage_AutoSaveInterval_3Min => ResourceManager.GetString(nameof(Storage_AutoSaveInterval_3Min), _resourceCulture);

        public static string Storage_AutoSaveInterval_5Min => ResourceManager.GetString(nameof(Storage_AutoSaveInterval_5Min), _resourceCulture);

        public static string Storage_AutoSaveInterval_60Min => ResourceManager.GetString(nameof(Storage_AutoSaveInterval_60Min), _resourceCulture);

        public static string Storage_AutoScreenshotOnClear => ResourceManager.GetString(nameof(Storage_AutoScreenshotOnClear), _resourceCulture);

        public static string Storage_Backups_Desc => ResourceManager.GetString(nameof(Storage_Backups_Desc), _resourceCulture);

        public static string Storage_Backups_Header => ResourceManager.GetString(nameof(Storage_Backups_Header), _resourceCulture);

        public static string Storage_CalculateFailed => ResourceManager.GetString(nameof(Storage_CalculateFailed), _resourceCulture);

        public static string Storage_Calculating => ResourceManager.GetString(nameof(Storage_Calculating), _resourceCulture);

        public static string Storage_CategoryDetails => ResourceManager.GetString(nameof(Storage_CategoryDetails), _resourceCulture);

        public static string Storage_Clean => ResourceManager.GetString(nameof(Storage_Clean), _resourceCulture);

        public static string Storage_CleanFailed => ResourceManager.GetString(nameof(Storage_CleanFailed), _resourceCulture);

        public static string Storage_Confirm_Body => ResourceManager.GetString(nameof(Storage_Confirm_Body), _resourceCulture);

        public static string Storage_Confirm_Second_Body => ResourceManager.GetString(nameof(Storage_Confirm_Second_Body), _resourceCulture);

        public static string Storage_Confirm_Second_Title => ResourceManager.GetString(nameof(Storage_Confirm_Second_Title), _resourceCulture);

        public static string Storage_Confirm_Title => ResourceManager.GetString(nameof(Storage_Confirm_Title), _resourceCulture);

        public static string Storage_CopyScreenshotToClipboard => ResourceManager.GetString(nameof(Storage_CopyScreenshotToClipboard), _resourceCulture);

        public static string Storage_Core_Desc => ResourceManager.GetString(nameof(Storage_Core_Desc), _resourceCulture);

        public static string Storage_Core_NotCleanable => ResourceManager.GetString(nameof(Storage_Core_NotCleanable), _resourceCulture);

        public static string Storage_Custom_Desc => ResourceManager.GetString(nameof(Storage_Custom_Desc), _resourceCulture);

        public static string Storage_Custom_Header => ResourceManager.GetString(nameof(Storage_Custom_Header), _resourceCulture);

        public static string Storage_Custom_Hint => ResourceManager.GetString(nameof(Storage_Custom_Hint), _resourceCulture);

        public static string Storage_DiskPercent => ResourceManager.GetString(nameof(Storage_DiskPercent), _resourceCulture);

        public static string Storage_Ink_Desc => ResourceManager.GetString(nameof(Storage_Ink_Desc), _resourceCulture);

        public static string Storage_Ink_Header => ResourceManager.GetString(nameof(Storage_Ink_Header), _resourceCulture);

        public static string Storage_Legend_Backups => ResourceManager.GetString(nameof(Storage_Legend_Backups), _resourceCulture);

        public static string Storage_Legend_Core => ResourceManager.GetString(nameof(Storage_Legend_Core), _resourceCulture);

        public static string Storage_Legend_Custom => ResourceManager.GetString(nameof(Storage_Legend_Custom), _resourceCulture);

        public static string Storage_Legend_Ink => ResourceManager.GetString(nameof(Storage_Legend_Ink), _resourceCulture);

        public static string Storage_Legend_Other => ResourceManager.GetString(nameof(Storage_Legend_Other), _resourceCulture);

        public static string Storage_Legend_Update => ResourceManager.GetString(nameof(Storage_Legend_Update), _resourceCulture);

        public static string Storage_Legend_Plugins => ResourceManager.GetString(nameof(Storage_Legend_Plugins), _resourceCulture);

        public static string Storage_Logs_Desc => ResourceManager.GetString(nameof(Storage_Logs_Desc), _resourceCulture);

        public static string Storage_Logs_Header => ResourceManager.GetString(nameof(Storage_Logs_Header), _resourceCulture);

        public static string Storage_NavTitle => ResourceManager.GetString(nameof(Storage_NavTitle), _resourceCulture);

        public static string Storage_NavTooltip => ResourceManager.GetString(nameof(Storage_NavTooltip), _resourceCulture);

        public static string Storage_OpenAppFolder => ResourceManager.GetString(nameof(Storage_OpenAppFolder), _resourceCulture);

        public static string Storage_Other_Desc => ResourceManager.GetString(nameof(Storage_Other_Desc), _resourceCulture);

        public static string Storage_PathBrowse => ResourceManager.GetString(nameof(Storage_PathBrowse), _resourceCulture);

        public static string Storage_Plugins_Desc => ResourceManager.GetString(nameof(Storage_Plugins_Desc), _resourceCulture);

        public static string Storage_Plugins_Header => ResourceManager.GetString(nameof(Storage_Plugins_Header), _resourceCulture);

        public static string Storage_Plugins_Hint => ResourceManager.GetString(nameof(Storage_Plugins_Hint), _resourceCulture);

        public static string Storage_Refresh => ResourceManager.GetString(nameof(Storage_Refresh), _resourceCulture);

        public static string Storage_SaveAsXml => ResourceManager.GetString(nameof(Storage_SaveAsXml), _resourceCulture);

        public static string Storage_SaveAsUInk => ResourceManager.GetString(nameof(Storage_SaveAsUInk), _resourceCulture);

        public static string Storage_SaveFullPageStrokes => ResourceManager.GetString(nameof(Storage_SaveFullPageStrokes), _resourceCulture);

        public static string Storage_ScreenshotSaveLocation => ResourceManager.GetString(nameof(Storage_ScreenshotSaveLocation), _resourceCulture);

        public static string Storage_ScreenshotSaveLocationDesc => ResourceManager.GetString(nameof(Storage_ScreenshotSaveLocationDesc), _resourceCulture);

        public static string Storage_ScreenshotsByDateFolder => ResourceManager.GetString(nameof(Storage_ScreenshotsByDateFolder), _resourceCulture);

        public static string Storage_ScreenshotSettings => ResourceManager.GetString(nameof(Storage_ScreenshotSettings), _resourceCulture);

        public static string Storage_ScreenshotSettingsDesc => ResourceManager.GetString(nameof(Storage_ScreenshotSettingsDesc), _resourceCulture);

        public static string Storage_ScreenshotFormat => ResourceManager.GetString(nameof(Storage_ScreenshotFormat), _resourceCulture);

        public static string Storage_ScreenshotJpegQuality => ResourceManager.GetString(nameof(Storage_ScreenshotJpegQuality), _resourceCulture);

        public static string Storage_ScreenshotScale => ResourceManager.GetString(nameof(Storage_ScreenshotScale), _resourceCulture);

        public static string Storage_ScreenshotScale_100 => ResourceManager.GetString(nameof(Storage_ScreenshotScale_100), _resourceCulture);

        public static string Storage_ScreenshotScale_75 => ResourceManager.GetString(nameof(Storage_ScreenshotScale_75), _resourceCulture);

        public static string Storage_ScreenshotScale_50 => ResourceManager.GetString(nameof(Storage_ScreenshotScale_50), _resourceCulture);

        public static string Storage_ScreenshotScale_25 => ResourceManager.GetString(nameof(Storage_ScreenshotScale_25), _resourceCulture);

        public static string Storage_Title => ResourceManager.GetString(nameof(Storage_Title), _resourceCulture);

        public static string Storage_TotalUsage => ResourceManager.GetString(nameof(Storage_TotalUsage), _resourceCulture);

        public static string Storage_Update_Desc => ResourceManager.GetString(nameof(Storage_Update_Desc), _resourceCulture);

        public static string Storage_Update_Header => ResourceManager.GetString(nameof(Storage_Update_Header), _resourceCulture);

        public static string Storage_Legend_Theme => ResourceManager.GetString(nameof(Storage_Legend_Theme), _resourceCulture);

        public static string Storage_Theme_Desc => ResourceManager.GetString(nameof(Storage_Theme_Desc), _resourceCulture);

        public static string Storage_Theme_Header => ResourceManager.GetString(nameof(Storage_Theme_Header), _resourceCulture);

        public static string Storage_Theme_Hint => ResourceManager.GetString(nameof(Storage_Theme_Hint), _resourceCulture);

        public static string Backup_SuccessTitle => ResourceManager.GetString(nameof(Backup_SuccessTitle), _resourceCulture);

        public static string Backup_SuccessMsg => ResourceManager.GetString(nameof(Backup_SuccessMsg), _resourceCulture);

        public static string Backup_FailedTitle => ResourceManager.GetString(nameof(Backup_FailedTitle), _resourceCulture);

        public static string Backup_CreateFailedMsg => ResourceManager.GetString(nameof(Backup_CreateFailedMsg), _resourceCulture);

        public static string Restore_FailedTitle => ResourceManager.GetString(nameof(Restore_FailedTitle), _resourceCulture);

        public static string Restore_NoBackupFound => ResourceManager.GetString(nameof(Restore_NoBackupFound), _resourceCulture);

        public static string Restore_FilterLabel => ResourceManager.GetString(nameof(Restore_FilterLabel), _resourceCulture);

        public static string Restore_AllJsonFilter => ResourceManager.GetString(nameof(Restore_AllJsonFilter), _resourceCulture);

        public static string Restore_SelectFileTitle => ResourceManager.GetString(nameof(Restore_SelectFileTitle), _resourceCulture);

        public static string Restore_ConfirmTitle => ResourceManager.GetString(nameof(Restore_ConfirmTitle), _resourceCulture);

        public static string Restore_ConfirmMsg => ResourceManager.GetString(nameof(Restore_ConfirmMsg), _resourceCulture);

        public static string Restore_SuccessTitle => ResourceManager.GetString(nameof(Restore_SuccessTitle), _resourceCulture);

        public static string Restore_SuccessMsg => ResourceManager.GetString(nameof(Restore_SuccessMsg), _resourceCulture);

        public static string Restore_ParseFailed => ResourceManager.GetString(nameof(Restore_ParseFailed), _resourceCulture);

        public static string Restore_FailedMsg => ResourceManager.GetString(nameof(Restore_FailedMsg), _resourceCulture);
    }
}