<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>InkCanvas.SettingsTreeView</RootNamespace>
    <AssemblyName>InkCanvas.SettingsTreeView</AssemblyName>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <LangVersion>10</LangVersion>
    <NoWarn>CA1416;NETSDK1138</NoWarn>
    <CetCompat>false</CetCompat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
    <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
  </ItemGroup>

</Project>
